Adding support for fallback domains
cloudflare/terraform-provider-cloudflare pull request #1356
Opened 2021-12-22 16:36 UTC by kjhandy

2021-12-22 18:31 UTC, patryk requested changes
Missing documentation, tests failing, improper cloudflare-go fields usage.

2021-12-22 19:50 UTC, kjhandy commented
Added documentation. Tests should all pass once cloudflare-go is bumped (depends on https://github.com/cloudflare/cloudflare-go/pull/761).

2022-01-06 20:47 UTC, kjhandy commented
@patryk I _believe_ this is waiting on a cloudflare-go release and to bump the version here. Is there a plan to do that?

2022-01-13 01:58 UTC, jacobbednarz commented on cloudflare/resource_cloudflare_fallback_domain_test.go
> +    host = "%[4]s"
should this be `suffix`?

```
=== RUN   TestAccCloudflareFallbackDomain
    resource_cloudflare_fallback_domain_test.go:25: Step 1/2 error: Error running pre-apply refresh: exit status 1

        Error: Unsupported argument

          on terraform_plugin_test.tf line 6, in resource "cloudflare_fallback_domain" "hjygxhxvvw":
           6:     host = "example.com"

        An argument named "host" is not expected here.
```

2022-01-13 01:59 UTC, jacobbednarz commented on cloudflare/resource_cloudflare_fallback_domain_test.go
> +					resource.TestCheckResourceAttr(name, "domains.0.dns_server", "['2.2.2.2']"),
i think you want the first entry in the slice here

```suggestion
					resource.TestCheckResourceAttr(name, "domains.0.dns_server.0", "2.2.2.2"),
```

2022-01-13 01:59 UTC, jacobbednarz commented on cloudflare/resource_cloudflare_fallback_domain_test.go
> +					resource.TestCheckResourceAttr(name, "domains.0.dns_server", "['1.1.1.1']"),
same as above, i think you want the first entry.

```suggestion
					resource.TestCheckResourceAttr(name, "domains.0.dns_server.0", "1.1.1.1"),
```

2022-01-13 02:00 UTC, jacobbednarz commented on website/docs/r/fallback_domain.html.markdown
> +sidebar_current: "docs-cloudflare-resource-fallback-domain"
don't forget to add a link this to document in https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/cloudflare.erb so it appears in the sidebar.

2022-01-13 02:37 UTC, merged