WDAPI-1066 add os_distro_name and os_distro_revision
cloudflare/terraform-provider-cloudflare pull request #1842
Opened 2022-08-17 21:59 UTC by dhens

update os_version device posture terraform docs for new linux fields

2022-08-17 23:51 UTC, jacobbednarz requested changes
you'll need to check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how to have this documentation updated as `docs` is the automatically generated version of these files.

2022-08-19 17:29 UTC, dhens commented
> you'll need to check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how to have this documentation updated as `docs` is the automatically generated version of these files.

I see, my bad. Thanks!

2022-08-26 00:00 UTC, jacobbednarz commented on templates/resources/device_posture_rule.md
> +- `os_distro_revision` = (Optional) The operating system version excluding OS name information or release name.
```suggestion
- `version` - (Required) The operating system semantic version.
- `operator` - (Required) The version comparison operator in (>,>=,<,<=,==)
- `os_distro_name` - (Optional) The operating system excluding version information.
- `os_distro_revision` - (Optional) The operating system version excluding OS name information or release name.
```

2022-08-26 00:03 UTC, jacobbednarz commented on templates/resources/device_posture_rule.md
> +    os_distro_revision = 1.0.0
these fields aren't present in the schema or public API docs; so we won't be able to add them at this time.

2022-08-26 00:03 UTC, jacobbednarz requested changes
you're referencing non-existing API fields and schema values so this is unable to be merged. i'd suggest first getting the fields documentated then added to cloudflare-go before attempting to add them here.

2022-09-01 02:57 UTC, jacobbednarz commented
these fields are now present in the Go library so you can add them to the schema, CRUD operations and the docs.

2022-09-09 03:31 UTC, jacobbednarz commented
i've pushed a few fixes here but the test suite is still failing with a service error. do you mind looking into this and getting the tests in the right shape?

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareDevicePostureRule_" -count 1 -parallel 1 -timeout 120m -parallel 1
?       github.com/cloudflare/terraform-provider-cloudflare     [no test files]
=== RUN   TestAccCloudflareDevicePostureRule_SerialNumber
--- PASS: TestAccCloudflareDevicePostureRule_SerialNumber (20.79s)
=== RUN   TestAccCloudflareDevicePostureRule_OsVersion
--- PASS: TestAccCloudflareDevicePostureRule_OsVersion (17.22s)
=== RUN   TestAccCloudflareDevicePostureRule_OsDistroName
    resource_cloudflare_device_posture_rule_test.go:103: Step 1/1 error: Error running apply: exit status 1

        Error: error creating Device Posture Rule for account "f037e56e89293a057740de681ac9abbe": access.api.error.invalid_device_posture_integration_type (12094)

          with cloudflare_device_posture_rule.phnddkhwtf,
          on terraform_plugin_test.tf line 2, in resource "cloudflare_device_posture_rule" "phnddkhwtf":
           2: resource "cloudflare_device_posture_rule" "phnddkhwtf" {

--- FAIL: TestAccCloudflareDevicePostureRule_OsDistroName (3.37s)
=== RUN   TestAccCloudflareDevicePostureRule_OsDistroRevision
    resource_cloudflare_device_posture_rule_test.go:140: Step 1/1 error: Error running apply: exit status 1

        Error: error creating Device Posture Rule for account "f037e56e89293a057740de681ac9abbe": access.api.error.invalid_device_posture_integration_type (12094)

          with cloudflare_device_posture_rule.xihdkeyskf,
          on terraform_plugin_test.tf line 2, in resource "cloudflare_device_posture_rule" "xihdkeyskf":
           2: resource "cloudflare_device_posture_rule" "xihdkeyskf" {

--- FAIL: TestAccCloudflareDevicePostureRule_OsDistroRevision (3.36s)
=== RUN   TestAccCloudflareDevicePostureRule_DomainJoined
--- PASS: TestAccCloudflareDevicePostureRule_DomainJoined (24.96s)
=== RUN   TestAccCloudflareDevicePostureRule_Firewall
--- PASS: TestAccCloudflareDevicePostureRule_Firewall (15.92s)
=== RUN   TestAccCloudflareDevicePostureRule_DiskEncryption
--- PASS: TestAccCloudflareDevicePostureRule_DiskEncryption (23.11s)
FAIL
FAIL    github.com/cloudflare/terraform-provider-cloudflare/internal/provider   109.388s
?       github.com/cloudflare/terraform-provider-cloudflare/version     [no test files]
FAIL
make: *** [testacc] Error 1
```

2022-09-14 23:00 UTC, jacobbednarz commented
depends on cloudflare/cloudflare-go#1087

2022-09-14 23:01 UTC, jacobbednarz commented
with the upstream PR shimmed in, tests are passing

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareDevicePostureRule_" -count 1 -parallel 1 -timeout 120m -parallel 1
?       github.com/cloudflare/terraform-provider-cloudflare     [no test files]
=== RUN   TestAccCloudflareDevicePostureRule_SerialNumber
--- PASS: TestAccCloudflareDevicePostureRule_SerialNumber (16.55s)
=== RUN   TestAccCloudflareDevicePostureRule_OsVersion
--- PASS: TestAccCloudflareDevicePostureRule_OsVersion (15.39s)
=== RUN   TestAccCloudflareDevicePostureRule_LinuxOsDistro
--- PASS: TestAccCloudflareDevicePostureRule_LinuxOsDistro (12.75s)
=== RUN   TestAccCloudflareDevicePostureRule_DomainJoined
--- PASS: TestAccCloudflareDevicePostureRule_DomainJoined (15.87s)
=== RUN   TestAccCloudflareDevicePostureRule_Firewall
--- PASS: TestAccCloudflareDevicePostureRule_Firewall (17.78s)
=== RUN   TestAccCloudflareDevicePostureRule_DiskEncryption
--- PASS: TestAccCloudflareDevicePostureRule_DiskEncryption (17.27s)
PASS
ok      github.com/cloudflare/terraform-provider-cloudflare/internal/provider   96.001s
?       github.com/cloudflare/terraform-provider-cloudflare/version     [no test files]
```

2022-09-28 00:47 UTC, merged