Suggest a better default value for root_dir in pages_project docs
cloudflare/terraform-provider-cloudflare pull request #2440
Opened 2023-05-17 09:57 UTC by jamielinux

Fixes https://github.com/cloudflare/terraform-provider-cloudflare/issues/2439

`root_dir = "/"` results in a Pages project that has `root_dir` of `//` (double slash).

2023-05-18 00:27 UTC, jacobbednarz requested changes

2023-05-18 00:27 UTC, jacobbednarz commented on docs/resources/pages_project.md
this file is a generated artifact. check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how to change these files and not have them overridden on the next run.

2023-05-18 06:51 UTC, jamielinux commented on docs/resources/pages_project.md
Sorry, I should have read that contributing readme! I've updated the PR.

2023-05-18 23:52 UTC, jacobbednarz commented
@WalshyDev does it also make sense to update the schema description with something like "omit the trailing slash"? https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/schema_cloudflare_pages_project.go#L24

2023-05-19 19:54 UTC, WalshyDev commented
Thank you for this fix @jamielinux 

@jacobbednarz yes definitely. The copy we use in the UI is "Your project’s root directory, where Cloudflare runs the build command. If your site is not in a subdirectory, leave this path value empty."

2023-05-21 23:14 UTC, jacobbednarz commented
thanks @WalshyDev - have updated the schema to use the same one. feel free to open a larger PR with any copy changes if you'd like it closer to the UI copy across the board.

2023-05-21 23:14 UTC, merged