Add Regional Tiered Cache resource
cloudflare/terraform-provider-cloudflare pull request #2624
Opened 2023-07-20 18:13 UTC by joshuamsager

Depends on https://github.com/cloudflare/cloudflare-go/tree/v0.73.0

Resolves: https://github.com/cloudflare/terraform-provider-cloudflare/issues/2615

Implements the following terraform resource:
```
resource "cloudflare_regional_tiered_cache" "settings" {
  zone_id                      = "my_zone_id"
  value                          = "on"
}
```

Open to changing the name of the resource/schema.

TODO:
- Generate documentation with `make docs`. Couldn't do this because of pending errors required when resolving the cloudflare-go API version upgrade.

2023-07-20 18:13 UTC, joshuamsager commented on internal/sdkv2provider/resource_cloudflare_regional_tiered_cache.go
> +			This can help improve performance for smart and custom tiered cache topologies.
Taken from: https://developers.cloudflare.com/api/operations/zone-cache-settings-change-regional-tiered-cache-setting

2023-07-20 20:23 UTC, jacobbednarz requested changes
notes in automation

2023-07-21 05:33 UTC, jacobbednarz commented
acceptance tests are passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareRegionalTieredCache_Basic" -count 1 -timeout 120m -parallel 1
Notice: Behaving like ASDF_GOLANG_MOD_VERSION_ENABLED=true
        In the future this will have to be set to continue
        reading from the go.mod and go.work files
=== RUN   TestAccCloudflareRegionalTieredCache_Basic
=== PAUSE TestAccCloudflareRegionalTieredCache_Basic
=== CONT  TestAccCloudflareRegionalTieredCache_Basic
--- PASS: TestAccCloudflareRegionalTieredCache_Basic (8.91s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	9.837s
```

2023-07-21 05:35 UTC, jacobbednarz commented
> * Generate documentation with `make docs`. Couldn't do this because of pending errors when resolving the cloudflare-go API version upgrade.

for future, you can work around this by running the following (and having cloudflare-go locally)

```
go mod edit -replace github.com/cloudflare/cloudflare-go=/path/to/cloudflare-go/locally
```

allows you to test without waiting for a full release :)

2023-07-21 05:35 UTC, merged

2023-07-21 05:36 UTC, jacobbednarz commented
thanks for these PRs @joshuamsager, it's appreciated!