create virtual network
cloudflare/terraform-provider-cloudflare pull request #2867
Opened 2023-10-21 19:33 UTC by danquack

relates to #2720

2023-10-22 23:57 UTC, jacobbednarz commented on internal/sdkv2provider/data_source_tunnel_virtual_network.go
> +		return diag.FromErr(fmt.Errorf("failed to fetch Cloudflare TunnelVirtualNetwork: %w", err))
```suggestion
		return diag.FromErr(fmt.Errorf("failed to fetch Tunnel Virtual Networks: %w", err))
```

2023-10-22 23:57 UTC, jacobbednarz commented on internal/sdkv2provider/data_source_tunnel_virtual_network.go
> +		return diag.FromErr(fmt.Errorf("No TunnelVirtualNetwork with name: %s", d.Get("name").(string)))
```suggestion
		return diag.FromErr(fmt.Errorf("No Tunnel Virtual Networks found with name: %s", d.Get("name").(string)))
```

2023-10-22 23:58 UTC, jacobbednarz commented on docs/data-sources/tunnel_virtual_network.md
thanks for the PR! unfortunately, the file you've edited is a generated artifact of the documentation process. to see how to make changes to the documentation, you're best to check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md

2023-10-22 23:58 UTC, jacobbednarz requested changes
similar to #2866, a couple of nitpicks to resolve but solid effort. thanks!

2023-10-23 01:36 UTC, jacobbednarz commented
acceptance tests all passing

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareTunneVirtualNetwork_MatchName" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareTunneVirtualNetwork_MatchName
--- PASS: TestAccCloudflareTunneVirtualNetwork_MatchName (10.32s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	11.032s
```

appreciate the PR @danquack 🙇

2023-10-23 01:37 UTC, danquack commented
@jacobbednarz appreciate you... are you using your user api key or token? I was struggling to find the proper permissions on my token auth

2023-10-23 01:38 UTC, jacobbednarz commented
both work for me. my API token is pretty broad though and will cover most permissions indiscriminately to avoid exactly that issue with the test suite 😛

2023-10-23 01:38 UTC, merged