Add acceptance test generator
cloudflare/terraform-provider-cloudflare pull request #4819
Opened 2024-12-27 21:32 UTC by musa-cf

Happy path example:
```
> go run cmd/acctestgen/main.go new_service

To be created:
- file: internal/services/new_service/data_source_test.go
- file: internal/services/new_service/resource_test.go
- dir: internal/services/new_service/testdata/
- file: internal/services/new_service/testdata/resourcebasicconfig.tf
- file: internal/services/new_service/testdata/datasourcebasicconfig.tf

Do you confirm that the file paths above are correct? [y|n]: y

The files have been created. To run the acceptance tests, you will need to first
set the necessary environment variables. See https://github.com/cloudflare/terraform-provider-cloudflare/blob/v4.39.0/contributing/environment-variable-dictionary.md
for the list of variables. The values will vary depending on the account and zone being used for
the tests. Once the environment variables are set, you can run the tests using the command:

TF_ACC=1 go test ./internal/services/new_service -run "^TestAccCloudflare" -v -count 1s
```

With `-dryrun` flag:
```
> go run cmd/acctestgen/main.go -dryrun new_service

To be created:
- file: internal/services/new_service/data_source_test.go
- file: internal/services/new_service/resource_test.go
- dir: internal/services/new_service/testdata/
- file: internal/services/new_service/testdata/resourcebasicconfig.tf
- file: internal/services/new_service/testdata/datasourcebasicconfig.tf

Dry-run mode is enabled.

To create the files, run this again without the 'dryrun' flag

Example: go run cmd/acctest/main.go new_service
```

Error case:
```
go run cmd/acctestgen/main.go -dryrun fwaefawef

ERROR: service 'fwaefawef' not found

exit status 1
```

2025-01-01 23:10 UTC, jacobbednarz requested changes
at a high level, i'm 👍 . two things we should do though to make the UX more consistent here are:

1) we move this into `tools/` given we aren't expecting the consumer of the library to use this. it's internal only and should be stripped from the end package that terraform consumes. check out the current `master` version of this for some inspiration.
2) this should be wrapped in a `scripts/...` execution. the goal of the `scripts` directory is to have a unified interface with how we expose tooling to operators. a deeper read on this is at https://github.com/github/scripts-to-rule-them-all but in essence, it means we maintain this pattern for all of the repositories.

2025-01-01 23:10 UTC, jacobbednarz commented on cmd/acctestgen/main.go
> +	datasourceDataPath := fmt.Sprintf("internal/services/%s/testdata/datasourcebasicconfig.tf", service)
we can probably refine the names here. given they are packaged now whereas the migration needed to keep the names for the purposes of tracking.

```suggestion
	resourceDataPath := fmt.Sprintf("internal/services/%s/testdata/basic.tf", service)
	datasourceDataPath := fmt.Sprintf("internal/services/%s/testdata/datasource_basic.tf", service)
```

2025-01-01 23:10 UTC, jacobbednarz commented on cmd/acctestgen/main.go
> +	fmt.Println()
nit: i would go with a multi line string here instead for readability.

```suggestion
	fmt.Println(fmt.Sprintf(`To be created:
- file:       %[1]s
- file:       %[2]s
- directory:  %[3]s
- file:       %[4]s
- file:       %[5]s
`, datasourcePath, resourcePath, testdataDirPath, resourceDataPath, datasourceDataPath)
```

2025-01-01 23:10 UTC, jacobbednarz commented on cmd/acctestgen/main.go
> +func test{{.PascalCase}}Config(rnd string) string {
```suggestion
func testAcc{{.PascalCase}}Config(rnd string) string {
```

2025-01-01 23:10 UTC, jacobbednarz commented on cmd/acctestgen/main.go
> +func test{{.PascalCase}}DataSourceConfig(rnd string) string {
```suggestion
func testAcc{{.PascalCase}}DataSourceConfig(rnd string) string {
```

2025-01-03 22:22 UTC, musa-cf commented
@jacobbednarz Thanks for the feedback! I've pushed a new commit with your suggestions.

2025-01-06 02:17 UTC, jacobbednarz commented on scripts/generate-acctests
why is this a binary file?

2025-01-08 21:41 UTC, musa-cf commented on scripts/generate-acctests
Ah, fixed. It's definitely not a binary anymore. 👍

2025-01-08 21:44 UTC, merged