Add support for zone-level routes to Access resources
cloudflare/terraform-provider-cloudflare pull request #819
Opened 2020-10-08 22:56 UTC by Justin-Holmes

Requires a new cloudflare-go version with https://github.com/cloudflare/cloudflare-go/pull/538 before this can be merged.

2020-10-08 22:58 UTC, Justin-Holmes commented
@jacobbednarz would love your opinion on this approach before I implement this for the remaining resources!

2020-10-09 03:59 UTC, jacobbednarz reviewed
I'm on board with this approach 👍 My initial concerns were that this is going to get unwieldy with these conditionals in each CRUD method however I can't think a better way of getting it without sacrificing readability and introducing some ✨ magic methods ✨ but it will make life pretty hard to debug when the time comes so let's give this a whirl.

2020-10-09 03:59 UTC, jacobbednarz commented on cloudflare/resource_cloudflare_access_application.go
> +				Computed: true,
Should we add some schema level validation here via `ConflictsWith: []string{"other_attr"}` to make sure that we only ever have `zone_id` or `account_id`?

2020-10-13 16:43 UTC, patryk requested changes
Need documentation changes and remove go.mod/sum from the PR, then we're good to merge.

2020-10-13 21:04 UTC, jacobbednarz commented
A thought for the documentation - It would be great if we could explicitly call out which uses cases fit `account_id` and `zone_id` so that we can have that as a reference point when debugging or digging into any issues that pop up.

2020-10-13 21:23 UTC, Justin-Holmes commented
@jacobbednarz Sure thing! Do you have a particular place in the documentation you'd like to me to add the notes?

2020-10-13 21:44 UTC, jacobbednarz commented
Nothing specific in mind so happy to defer to your best judgement on what explains it best. I'm just after an easy reference/guide for determining which one should be used. Some examples that come to mind are things like:

- Full HCL examples;
- Note in the attributes reference section; 
- Callout on the documentation (like https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack). Available callouts are documented at https://github.com/hashicorp/terraform-website#callouts

2020-10-14 12:10 UTC, patryk approved these changes

2020-10-16 14:28 UTC, merged