Exposing default_mode of WAF Rule through cloudflare_waf_rules data source
cloudflare/terraform-provider-cloudflare pull request #980
Opened 2021-03-07 17:41 UTC by JoseRoman

#979

2021-03-07 22:08 UTC, jacobbednarz commented
seems reasonable 👍 can you please add test coverage for this new attribute?

2021-03-08 14:37 UTC, JoseRoman commented
@jacobbednarz Of course, I can add some tests for this.

- What is the process of running the acceptance tests locally? Do I have to create a test Cloudflare account to be able to run them? 
- This is a read-only field (similar to `allowed_modes`) that is not being filtered, do we still write tests for these?

2021-03-08 20:25 UTC, jacobbednarz commented
> What is the process of running the acceptance tests locally? Do I have to create a test Cloudflare account to be able to run them?

There is a section in the README on [developing the provider](https://github.com/cloudflare/terraform-provider-cloudflare#developing-the-provider) which will step you through testing. Yes, you'll need a Cloudflare account as the tests create real resources.

> This is a read-only field (similar to allowed_modes) that is not being filtered, do we still write tests for these?

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/data_source_waf_rules_test.go#L13 is an example of an existing `data_source_waf_rules` test which you could copy, tweak and confirm your new fields are usable (either through confirming them being written to the state file or in another resource).

2021-03-10 04:20 UTC, jacobbednarz commented on cloudflare/data_source_waf_rules_test.go
> +					resource.TestCheckResourceAttrSet(name, "rules.#"),
i'm afraid this assertion doesn't do assert anything useful for us here. this test is identical to some others and doesn't actually cover the functionality you've added. 

perhaps have a look at `testAccCheckCloudflareWAFRulesDataSourceID` and i suspect you'll need to programmatically loop through the resource rules and confirm the key is present in the state following this change.

2021-03-10 04:21 UTC, jacobbednarz requested changes
we need to adjust the test case for this because as it stands, it is a duplicate of an existing test with a different name and doesn't cover the added fields being stored in state.

2021-06-23 03:58 UTC, jacobbednarz commented
closing in favour of #1079

2021-06-23 03:58 UTC, closed without merging